daemon:
    name: Production Cluster

general:
    eventlogger: 127.0.0.1:%LOGGER_PORT%
    dc_files:
        - ../dclass/otp.dc
        - ../dclass/pirates.dc

messagedirector:
    bind: 0.0.0.0:%MD_PORT%

uberdogs:
    - class: ClientServicesManager
      id: 1000
      anonymous: true

    - class: DistributedTravelAgent
      id: 1001
      anonymous: false

    - class: PiratesFriendsManager
      id: 1002
      anonymous: false
    
    - class: AvatarFriendsManager
      id: 1003
      anonymous: false
    
    - class: DistributedCrewMatchManager
      id: 1004
      anonymous: false
    
    - class: CentralLogger
      id: 1005
      anonymous: false

    - class: DistributedMatchMaker
      id: 1006
      anonymous: false

    - class: DistributedGuildManager
      id: 1007
      anonymous: false

roles:
    - type: stateserver
      control: %STATESERVER%

    - type: database
      control: 1101
      generate:
          min: 100000000
          max: 399999999
      backend:
        type: mongodb
        server: %MONGO_IP%

    - type: dbss
      database: 1101
      ranges:
          - min: 100000000
          - max: 399999999

    - type: eventlogger
      bind: 0.0.0.0:%LOGGER_PORT%
      output: ../logs/events-%y%m%d_%H%M%S.log
