daemon:
    name: Client Agent

general:
    eventlogger: %LOGGER_IP%
    dc_files:
        - ../dclass/otp.dc
        - ../dclass/pirates.dc

messagedirector:
    connect: %MD_IP%

uberdogs:
    - class: ClientServicesManager
      id: 1000
      anonymous: true

    - class: DistributedTravelAgent
      id: 1001
      anonymous: false

    - class: PiratesFriendsManager
      id: 1002
      anonymous: false
    
    - class: DistributedCrewMatchManager
      id: 1003
      anonymous: false

    - class: DistributedMatchMaker
      id: 1004
      anonymous: false

    - class: GuildManager
      id: 1005
      anonymous: false

roles:
    - type: clientagent
      bind: 0.0.0.0:29150
      version: "%VERSION%"
      client:
          relocate: true
          add_interest: enabled
          send_hash: false
          send_version: false
      channels:
          min: 1000000000
          max: 1000001000